name: "DockerHub Push Action"
description: "Build and push Docker image to DockerHub"
inputs:
  repo:
    description: "Docker image name"
    required: true
  branch:
    description: "Branch name will be prefixed to image name as branch_repo_name:commit_hash"
    required: false
  commit-hash:
    description: "Commit hash"
    required: false
    default: "latest"
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password or PAT"
    required: true
  env-file:
    description: ".env file contents"
    required: false
  push:
    description: "Should it push image to docker"
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Parse Docker Image Name
      shell: bash
      id: image_name
      run: |
        # Docker username
        USERNAME=${{ inputs.docker-username }}
        # Get commit hash from input or default to "latest"
        COMMIT_HASH=${{ inputs.commit-hash || 'latest' }}

        # Construct the image name in the correct format
        IMAGE_NAME="${USERNAME}/${{ inputs.repo }}:${COMMIT_HASH}"

        # Output the image name for visibility
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "Docker Image Name: $IMAGE_NAME"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ inputs.push }}
        tags: ${{ env.IMAGE_NAME }}
        file: Dockerfile # Specify the Dockerfile path if it's not the default
